In [ ]:
import numpy as np

### SUM, MIN, MAX

In [13]:
big_array = np.random.rand(1000)
%timeit sum(big_array)
%timeit np.sum(big_array)

129 µs ± 603 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
2.44 µs ± 230 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
np.min(big_array), np.max(big_array)

(0.00098561856427836769, 0.99947556031324558)

In [15]:
%timeit min(big_array)
%timeit np.min(big_array)

48.8 µs ± 65 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
2.29 µs ± 6.81 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
print(big_array.min(), big_array.max(), big_array.sum())

0.000985618564278 0.999475560313 497.102229897


### Многомерные сводные показатели

In [17]:
M = np.random.random((3, 4))
print(M)

[[ 0.78234112  0.21550833  0.62292744  0.53012043]
 [ 0.2525845   0.12572385  0.05469664  0.38775828]
 [ 0.83382787  0.22656239  0.98431005  0.21766844]]


In [18]:
# минимальное значение каждого из столбцов
M.min(axis=0)

array([ 0.2525845 ,  0.12572385,  0.05469664,  0.21766844])

In [19]:
# максимальное значение в каждом из строк
M.max(axis=1)

array([ 0.78234112,  0.38775828,  0.98431005])

np.mean - среднее  
np.std - стандартное отклонение  
np.var - дисперсия  
np.median - медиана  
np.percentile - квантили  
np.any - существуют ли элементы со значением true  
np.all - все ли элементы имеют значение true  