# Атрибуты массивов

In [2]:
import numpy as np
np.random.seed(0) # начальное значение для целей воспроизводимости

x1 = np.random.randint(10, size=6) # одномерный массив
x2 = np.random.randint(10, size=(3, 4)) # двумерный массив
x3 = np.random.randint(10, size=(3, 4, 5)) # трехмерный массив

In [3]:
print("x3 ndim: ", x3.ndim) # размерность
print("x3 shape: ", x3.shape) # размер каждого измерения
print("x3 size: ", x3.size) # общий размер массив
print("x3 dtype: ", x3.dtype) # тип данных массива
print("x3 itemsize", x3.itemsize) # размер каждого элемента массива
print("x3 nbytes", x3.nbytes) # полный размер массива

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 dtype:  int32
x3 itemsize 4
x3 nbytes 240


# Индексация массива

In [4]:
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
x1[0]

5

In [7]:
x1[-1]

9

In [8]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [9]:
x2[0, 0]

3

In [11]:
x2[2, -1]

7

In [13]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# Срезы

x[start:stop:step]

## Одномерные подмассивы

In [15]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x[:5]

array([0, 1, 2, 3, 4])

In [17]:
x[5:]

array([5, 6, 7, 8, 9])

In [18]:
x[4:7]

array([4, 5, 6])

In [19]:
x[::2]

array([0, 2, 4, 6, 8])

In [20]:
x[1::2]

array([1, 3, 5, 7, 9])

In [21]:
x[::-1] # все элементы в обратном порядке

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [22]:
x[5::-1] # каждый второй элемент в обратном порядке, с 5

array([5, 4, 3, 2, 1, 0])

## Многомерные подмассивы

In [24]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [25]:
x2[:2, :3] # две строки, три солбца

array([[12,  5,  2],
       [ 7,  6,  8]])

In [26]:
x2[:3, ::2] # все строки, кждый второй столбец

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [27]:
x2[::-1, ::-1] # переворачиваем

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])