# Атрибуты массивов

In [49]:
import numpy as np
np.random.seed(0) # начальное значение для целей воспроизводимости

x1 = np.random.randint(10, size=6) # одномерный массив
x2 = np.random.randint(10, size=(3, 4)) # двумерный массив
x3 = np.random.randint(10, size=(3, 4, 5)) # трехмерный массив

In [50]:
print("x3 ndim: ", x3.ndim) # размерность
print("x3 shape: ", x3.shape) # размер каждого измерения
print("x3 size: ", x3.size) # общий размер массив
print("x3 dtype: ", x3.dtype) # тип данных массива
print("x3 itemsize", x3.itemsize) # размер каждого элемента массива
print("x3 nbytes", x3.nbytes) # полный размер массива

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 dtype:  int32
x3 itemsize 4
x3 nbytes 240


# Индексация массива

In [51]:
x1

array([5, 0, 3, 3, 7, 9])

In [52]:
x1[0]

5

In [53]:
x1[-1]

9

In [54]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [55]:
x2[0, 0]

3

In [56]:
x2[2, -1]

7

In [57]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# Срезы

x[start:stop:step]

## Одномерные подмассивы

In [58]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
x[:5]

array([0, 1, 2, 3, 4])

In [60]:
x[5:]

array([5, 6, 7, 8, 9])

In [61]:
x[4:7]

array([4, 5, 6])

In [62]:
x[::2]

array([0, 2, 4, 6, 8])

In [63]:
x[1::2]

array([1, 3, 5, 7, 9])

In [64]:
x[::-1] # все элементы в обратном порядке

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [65]:
x[5::-1] # каждый второй элемент в обратном порядке, с 5

array([5, 4, 3, 2, 1, 0])

## Многомерные подмассивы

In [66]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [67]:
x2[:2, :3] # две строки, три солбца

array([[12,  5,  2],
       [ 7,  6,  8]])

In [68]:
x2[:3, ::2] # все строки, кждый второй столбец

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [69]:
x2[::-1, ::-1] # переворачиваем

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

### Доступ к строкам и столбцам массива

In [70]:
print(x2[:, 0]) # первый столбец x2

[12  7  1]


In [71]:
print(x2[0, :]) # первая строка массива x2

[12  5  2  4]


In [72]:
print(x2[0]) # эквивалентно x2[0, :]

[12  5  2  4]


### Создание копий массивов

In [73]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[12  5]
 [ 7  6]]


## Изменение формы массивов

In [74]:
# Переносим числа от 1 до 9 в таблицу 3x3
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Преобразование одномерного массива в двумерную матрицу-строку или матрицу-столбец

In [75]:
x = np.array([1, 2, 3])

# Преобразование в вектор-строку с помощью reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [76]:
# Преобразование в вектор-строку newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [77]:
# Преобразование в вектор-столбец с помощью reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [78]:
# Преобразование в вектор-столбец newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Слияние и разбиение массивов

### Слияние массивов

np.concatenate, np.vstack, np.hstack

In [79]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [80]:
# три массива
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [81]:
# двумерные массивы
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
# слияние по первой оси координат
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [82]:
# слияние по второй оси координат (с индексом 0)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

np.vstack - вертикальное обьединение
np.hstack - горизонтальное обьединение

In [83]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
# Обьединяет массивы по вертикали
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [84]:
# Обьединяет массивы по горизонтали
y = np.array([[99],
             [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

np.dstack обьединяет массивы по третьей оси

### Разбиение массивов

np.split, np.hsplit, np.vsplit

In [85]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [86]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [88]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
