# Сравнения и маски

## Операторы сравнения для массивов

In [12]:
import numpy as np

In [13]:
x = np.array([1, 2, 3, 4, 5])

In [14]:
x < 3

array([ True,  True, False, False, False], dtype=bool)

In [15]:
x > 3 

array([False, False, False,  True,  True], dtype=bool)

In [16]:
x <= 3

array([ True,  True,  True, False, False], dtype=bool)

In [17]:
x >= 3

array([False, False,  True,  True,  True], dtype=bool)

In [18]:
x != 3 

array([ True,  True, False,  True,  True], dtype=bool)

In [19]:
x == 3

array([False, False,  True, False, False], dtype=bool)

In [20]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False], dtype=bool)

In [21]:
# двумерный массив
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [22]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]], dtype=bool)

### Булевы массивы

In [23]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [25]:
# сколько значений в массиве меньше 6
np.count_nonzero(x < 6)

8

In [26]:
# True = 1, False = 0
np.sum(x < 6)

8

In [27]:
# сколько значений 6 содержится по строкам
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [28]:
# Существуют в массиве элементы > 8
np.any(x > 8)

True

In [29]:
# все значения < 10
np.all(x < 10)

True

In [31]:
# по строкам
np.all(x < 8, axis=1)

array([ True, False,  True], dtype=bool)

## Булевы массивы как маски

In [33]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [34]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]], dtype=bool)

In [35]:
# наложение маски
# вернет массив заполнен значениями подходящие под условие
x[x < 5]

array([0, 3, 3, 3, 2, 4])