# Транслирование(Broadcasting)

In [2]:
import numpy as np

In [3]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [4]:
a + 5

array([5, 6, 7])

In [5]:
M = np.ones((3, 3))
M

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [6]:
M + a

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [7]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [8]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Пример 1
Сложение одномерного массива с двумерным

In [20]:
M = np.ones((2, 3))
a = np.arange(3)
print(M)
print(b)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[0 1 2]


In [21]:
print(M.shape)
print(b.shape)

(2, 3)
(3,)


Правило 1  
По сколько размерность массива a меньше, дополняем его измерением слева  
M.shape -> (2, 3)  
a.shape -> (1, 3)

Правило 2  
Первое измерение массивов различаются, по этому растягиваем его до совподения  
M.shape -> (2, 3)  
a.shape -> (2, 3)

In [19]:
M + a

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

### Пример 2
Траслирование двух масиивов

In [22]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a)
print(b)

[[0]
 [1]
 [2]]
[0 1 2]


In [16]:
print(a.shape)
print(b.shape)

(3, 1)
(3,)


Привило 1  
Дополняем b еденицами  
a.shape -> (3, 1)  
b.shape -> (1, 3)

Правило 2  
Добавляем еденицы до совподения  
a.shape -> (3, 3)  
b.shape -> (3, 3)

In [23]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Пример 3
Два массива не совместимы

In [25]:
M = np.ones((3, 2))
a = np.arange(3)
print(M)
print(b)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[0 1 2]


In [26]:
print(M.shape)
print(b.shape)

(3, 2)
(3,)


In [27]:
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [28]:
a[:, np.newaxis].shape

(3, 1)

In [29]:
M + a[:, np.newaxis]

array([[ 1.,  1.],
       [ 2.,  2.],
       [ 3.,  3.]])

In [30]:
np.logaddexp(M, a[:, np.newaxis])

array([[ 1.31326169,  1.31326169],
       [ 1.69314718,  1.69314718],
       [ 2.31326169,  2.31326169]])

## Центрирование массива

In [32]:
X = np.random.random((10, 3))
X

array([[ 0.06831117,  0.80570064,  0.26467577],
       [ 0.51279068,  0.53399499,  0.38122434],
       [ 0.07025656,  0.8596692 ,  0.61508758],
       [ 0.58143107,  0.28475197,  0.36428533],
       [ 0.16739631,  0.14298275,  0.01473494],
       [ 0.07758206,  0.78591844,  0.39235445],
       [ 0.22987393,  0.88992777,  0.48541926],
       [ 0.74345452,  0.92569732,  0.18065321],
       [ 0.27237834,  0.36049005,  0.40959529],
       [ 0.22384838,  0.41357934,  0.67148411]])

In [33]:
# среднее
Xmean = X.mean(0)
Xmean

array([ 0.2947323 ,  0.60027125,  0.37795143])

In [34]:
# центрирование 
X_centered = X - Xmean
X_centered

array([[-0.22642113,  0.20542939, -0.11327566],
       [ 0.21805838, -0.06627626,  0.00327291],
       [-0.22447575,  0.25939795,  0.23713615],
       [ 0.28669877, -0.31551927, -0.0136661 ],
       [-0.12733599, -0.4572885 , -0.36321648],
       [-0.21715024,  0.1856472 ,  0.01440302],
       [-0.06485837,  0.28965652,  0.10746783],
       [ 0.44872222,  0.32542607, -0.19729822],
       [-0.02235396, -0.2397812 ,  0.03164386],
       [-0.07088392, -0.18669191,  0.29353268]])

In [35]:
X_centered.mean(0)

array([  1.11022302e-17,  -2.22044605e-17,  -5.55111512e-17])

## График двумерно