In [1]:
import numpy as np

In [2]:
# массив целочисленных значений
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [3]:
# вложенные списки преобразуются в многомерные массивы
np.array([[range(i, i + 3)] for i in [2, 4, 6]])

array([[[2, 3, 4]],

       [[4, 5, 6]],

       [[6, 7, 8]]])

In [4]:
# создаем массив целых чисел длины 10, заполненый нулями
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# создаем массив размером 3х5 значений с плавающей точкой, заполненный единицами
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [7]:
# создаем массив размером 3х5, заполненный 3.14
np.full((3, 4), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14]])

In [8]:
# создаем массив, заполненный линейной последовательностью,
# начинающейся с 0 и заканчивающейся 20, с шагом 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# создаем массив размером 3х3 равномерно распределенных
# случайных значения от 0 до 1
np.random.random((3, 3))

array([[ 0.87507553,  0.60121224,  0.42470066],
       [ 0.58847979,  0.64706531,  0.24289087],
       [ 0.47074058,  0.24387344,  0.57266286]])

In [10]:
# создаем массив размером 3х3 случайных целых чисел в промежутке [0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 8, 9],
       [0, 0, 7],
       [8, 6, 7]])

In [11]:
# создаем единичную матрицу размером 3х3
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [12]:
# создаем неинициалированный массив из трех целочисленных значений.
# значениями будет произвольные, случайно оказавшиеся в памяти
np.empty(3)

array([ 1.,  1.,  1.])